# Generated by Django 5.2.18 on 2026-10-09 01:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid6
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0003_historicalpessoa_cnae_principal_and_more'),
        ('contratos', '0001_initial'),
        ('core', '0002_contador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTarefa',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('DESENVOLVIMENTO', 'Desenvolvimento'), ('CORRECAO', 'Correção'), ('SUPORTE', 'Suporte'), ('MANUTENCAO', 'Manutenção'), ('IMPLANTACAO', 'Implantação'), ('TREINAMENTO', 'Treinamento'), ('REUNIAO', 'Reunião'), ('CONTEUDO', 'Conteúdo'), ('INFRA', 'Infraestrutura')], default='SUPORTE', max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('A_FAZER', 'A fazer'), ('EM_ANDAMENTO', 'Em andamento'), ('EM_REVISAO', 'Em revisão'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='A_FAZER', editable=False, max_length=15)),
                ('protocolo_cliente', models.CharField(blank=True, max_length=100)),
                ('data_abertura', models.DateField(default=django.utils.timezone.localdate)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('horas_estimadas', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('entrar_no_relatorio', models.BooleanField(default=True, verbose_name='incluir no relatório')),
                ('resumo_para_relatorio', models.TextField(blank=True, verbose_name='resumo do que foi entregue')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contrato', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contratos.contrato')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.contato')),
            ],
            options={
                'verbose_name': 'historical tarefa',
                'verbose_name_plural': 'historical tarefas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('DESENVOLVIMENTO', 'Desenvolvimento'), ('CORRECAO', 'Correção'), ('SUPORTE', 'Suporte'), ('MANUTENCAO', 'Manutenção'), ('IMPLANTACAO', 'Implantação'), ('TREINAMENTO', 'Treinamento'), ('REUNIAO', 'Reunião'), ('CONTEUDO', 'Conteúdo'), ('INFRA', 'Infraestrutura')], default='SUPORTE', max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('A_FAZER', 'A fazer'), ('EM_ANDAMENTO', 'Em andamento'), ('EM_REVISAO', 'Em revisão'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='A_FAZER', editable=False, max_length=15)),
                ('protocolo_cliente', models.CharField(blank=True, max_length=100)),
                ('data_abertura', models.DateField(default=django.utils.timezone.localdate)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('horas_estimadas', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('entrar_no_relatorio', models.BooleanField(default=True, verbose_name='incluir no relatório')),
                ('resumo_para_relatorio', models.TextField(blank=True, verbose_name='resumo do que foi entregue')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='contratos.contrato')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.contato')),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalApontamento',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operacao.tarefa')),
            ],
            options={
                'verbose_name': 'historical apontamento de horas',
                'verbose_name_plural': 'historical apontamentos de horas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Apontamento',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apontamentos', to='operacao.tarefa')),
            ],
            options={
                'verbose_name': 'apontamento de horas',
                'verbose_name_plural': 'apontamentos de horas',
                'ordering': ['-data', '-criado_em'],
                'constraints': [models.CheckConstraint(condition=models.Q(('horas__gt', 0), ('horas__lte', 24)), name='apontamento_horas_validas')],
            },
        ),
    ]
