# Generated by Django 5.2.18 on 2026-10-09 04:44

import django.db.models.deletion
import simple_history.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('core', '0002_contador'),
        ('operacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRelatorioAtividades',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('competencia', models.DateField(verbose_name='competência')),
                ('versao', models.PositiveIntegerField(default=1, editable=False)),
                ('introducao', models.TextField(blank=True, verbose_name='introdução')),
                ('conteudo', models.TextField(max_length=30000, verbose_name='atividades e entregas')),
                ('consideracoes_finais', models.TextField(blank=True, verbose_name='considerações finais')),
                ('tarefas_snapshot', models.JSONField(blank=True, default=list, editable=False)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADO', 'Aprovado')], default='RASCUNHO', editable=False, max_length=12)),
                ('aprovado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aprovado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contratos.contrato')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pdf', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.anexo')),
            ],
            options={
                'verbose_name': 'historical relatorio atividades',
                'verbose_name_plural': 'historical relatorio atividadess',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RelatorioAtividades',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('competencia', models.DateField(verbose_name='competência')),
                ('versao', models.PositiveIntegerField(default=1, editable=False)),
                ('introducao', models.TextField(blank=True, verbose_name='introdução')),
                ('conteudo', models.TextField(max_length=30000, verbose_name='atividades e entregas')),
                ('consideracoes_finais', models.TextField(blank=True, verbose_name='considerações finais')),
                ('tarefas_snapshot', models.JSONField(blank=True, default=list, editable=False)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADO', 'Aprovado')], default='RASCUNHO', editable=False, max_length=12)),
                ('aprovado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('aprovado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_atividades', to='contratos.contrato')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('pdf', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.anexo')),
            ],
            options={
                'ordering': ['-competencia', '-versao'],
                'constraints': [models.UniqueConstraint(fields=('contrato', 'competencia', 'versao'), name='relatorio_atividades_versao')],
            },
        ),
    ]
