# Generated by Django 5.2.18 on 2026-10-09 05:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('core', '0003_alter_logintegracao_servico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSistema',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=400, verbose_name='endereço verificado')),
                ('metodo', models.CharField(choices=[('GET', 'GET'), ('HEAD', 'HEAD')], default='GET', max_length=4, verbose_name='método')),
                ('status_esperado', models.PositiveSmallIntegerField(default=200, verbose_name='HTTP esperado')),
                ('palavra_chave', models.CharField(blank=True, max_length=120, verbose_name='texto esperado na página')),
                ('intervalo_min', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='verificar a cada (min)')),
                ('timeout_s', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(60)], verbose_name='tempo limite (s)')),
                ('lento_ms', models.PositiveIntegerField(default=4000, verbose_name='considerar lento acima de (ms)')),
                ('falhas_para_alerta', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='falhas seguidas para alertar')),
                ('alertar_whatsapp', models.BooleanField(default=True, verbose_name='alertar no WhatsApp')),
                ('em_manutencao', models.BooleanField(default=False, verbose_name='em manutenção (sem alertas)')),
                ('status', models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('DEGRADADO', 'Lento'), ('FORA', 'Fora do ar'), ('MANUTENCAO', 'Em manutenção'), ('DESCONHECIDO', 'Aguardando verificação')], default='DESCONHECIDO', editable=False, max_length=12)),
                ('ultima_verificacao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ultimo_tempo_ms', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('ultimo_erro', models.CharField(blank=True, editable=False, max_length=300)),
                ('falhas_consecutivas', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('ultima_mudanca', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ssl_expira_em', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='certificado SSL expira em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contrato', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contratos.contrato')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sistema monitorado',
                'verbose_name_plural': 'historical sistemas monitorados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=400, verbose_name='endereço verificado')),
                ('metodo', models.CharField(choices=[('GET', 'GET'), ('HEAD', 'HEAD')], default='GET', max_length=4, verbose_name='método')),
                ('status_esperado', models.PositiveSmallIntegerField(default=200, verbose_name='HTTP esperado')),
                ('palavra_chave', models.CharField(blank=True, max_length=120, verbose_name='texto esperado na página')),
                ('intervalo_min', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='verificar a cada (min)')),
                ('timeout_s', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(60)], verbose_name='tempo limite (s)')),
                ('lento_ms', models.PositiveIntegerField(default=4000, verbose_name='considerar lento acima de (ms)')),
                ('falhas_para_alerta', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='falhas seguidas para alertar')),
                ('alertar_whatsapp', models.BooleanField(default=True, verbose_name='alertar no WhatsApp')),
                ('em_manutencao', models.BooleanField(default=False, verbose_name='em manutenção (sem alertas)')),
                ('status', models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('DEGRADADO', 'Lento'), ('FORA', 'Fora do ar'), ('MANUTENCAO', 'Em manutenção'), ('DESCONHECIDO', 'Aguardando verificação')], default='DESCONHECIDO', editable=False, max_length=12)),
                ('ultima_verificacao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ultimo_tempo_ms', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('ultimo_erro', models.CharField(blank=True, editable=False, max_length=300)),
                ('falhas_consecutivas', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('ultima_mudanca', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ssl_expira_em', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='certificado SSL expira em')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sistemas', to='contratos.contrato')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
            ],
            options={
                'verbose_name': 'sistema monitorado',
                'verbose_name_plural': 'sistemas monitorados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Em andamento'), ('FECHADO', 'Resolvido')], default='ABERTO', max_length=8)),
                ('causa', models.CharField(blank=True, max_length=300)),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='sla.sistema')),
            ],
            options={
                'verbose_name': 'incidente',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalIncidente',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Em andamento'), ('FECHADO', 'Resolvido')], default='ABERTO', max_length=8)),
                ('causa', models.CharField(blank=True, max_length=300)),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sistema', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sla.sistema')),
            ],
            options={
                'verbose_name': 'historical incidente',
                'verbose_name_plural': 'historical incidentes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Verificacao',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sucesso', models.BooleanField(default=False)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tempo_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('erro', models.CharField(blank=True, max_length=300)),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificacoes', to='sla.sistema')),
            ],
            options={
                'ordering': ['-em'],
                'indexes': [models.Index(fields=['sistema', 'em'], name='verificacao_sistema_em')],
            },
        ),
    ]
