# Generated by Django 5.2.18 on 2026-10-09 18:10

import django.db.models.deletion
import simple_history.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_documentocontrato_historicaldocumentocontrato'),
        ('core', '0004_historicalcontaemail_contaemail'),
        ('sla', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsistema',
            name='alertar_email',
            field=models.BooleanField(default=True, verbose_name='alertar por e-mail'),
        ),
        migrations.AddField(
            model_name='historicalsistema',
            name='emails_alerta',
            field=models.TextField(blank=True, help_text='Recebem os alertas só deste sistema (ex.: TI do cliente). Separe por vírgula.', verbose_name='e-mails deste sistema'),
        ),
        migrations.AddField(
            model_name='historicalsistema',
            name='incluir_gerais',
            field=models.BooleanField(default=True, verbose_name='enviar também aos destinatários gerais'),
        ),
        migrations.AddField(
            model_name='historicalsistema',
            name='meta_sla',
            field=models.DecimalField(decimal_places=2, default=99, help_text='Usada no relatório mensal de SLA.', max_digits=5, verbose_name='meta de disponibilidade (%)'),
        ),
        migrations.AddField(
            model_name='sistema',
            name='alertar_email',
            field=models.BooleanField(default=True, verbose_name='alertar por e-mail'),
        ),
        migrations.AddField(
            model_name='sistema',
            name='emails_alerta',
            field=models.TextField(blank=True, help_text='Recebem os alertas só deste sistema (ex.: TI do cliente). Separe por vírgula.', verbose_name='e-mails deste sistema'),
        ),
        migrations.AddField(
            model_name='sistema',
            name='incluir_gerais',
            field=models.BooleanField(default=True, verbose_name='enviar também aos destinatários gerais'),
        ),
        migrations.AddField(
            model_name='sistema',
            name='meta_sla',
            field=models.DecimalField(decimal_places=2, default=99, help_text='Usada no relatório mensal de SLA.', max_digits=5, verbose_name='meta de disponibilidade (%)'),
        ),
        migrations.CreateModel(
            name='HistoricalConfiguracaoAlertas',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('enviar_email', models.BooleanField(default=True, verbose_name='enviar alertas por e-mail')),
                ('emails_gerais', models.TextField(blank=True, help_text='Recebem alertas de todos os sistemas. Separe por vírgula ou ponto e vírgula.', verbose_name='destinatários gerais')),
                ('assunto_queda', models.CharField(default='🔴 {sistema} fora do ar', max_length=200, verbose_name='assunto (queda)')),
                ('corpo_queda', models.TextField(default='Olá,\n\nO monitoramento da KS TEC identificou que o sistema {sistema} está fora do ar desde {inicio}.\nEndereço: {url}\nMotivo: {erro}\n\nNossa equipe já foi acionada e você receberá um novo aviso quando o serviço for restabelecido.\n\nKS TEC Soluções de Tecnologia', verbose_name='mensagem (queda)')),
                ('assunto_retorno', models.CharField(default='🟢 {sistema} restabelecido', max_length=200, verbose_name='assunto (retorno)')),
                ('corpo_retorno', models.TextField(default='Olá,\n\nO sistema {sistema} voltou a operar normalmente. Período de indisponibilidade: {duracao} (início em {inicio}).\n\nKS TEC Soluções de Tecnologia', verbose_name='mensagem (retorno)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical configuração de alertas',
                'verbose_name_plural': 'historical configuração de alertass',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRelatorioSLA',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('competencia', models.DateField(verbose_name='competência')),
                ('versao', models.PositiveIntegerField(default=1, editable=False)),
                ('dados', models.JSONField(default=dict, editable=False)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADO', 'Aprovado')], default='RASCUNHO', editable=False, max_length=12)),
                ('aprovado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aprovado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contratos.contrato')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pdf', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.anexo')),
            ],
            options={
                'verbose_name': 'historical relatório de SLA',
                'verbose_name_plural': 'historical relatórios de SLA',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ConfiguracaoAlertas',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('enviar_email', models.BooleanField(default=True, verbose_name='enviar alertas por e-mail')),
                ('emails_gerais', models.TextField(blank=True, help_text='Recebem alertas de todos os sistemas. Separe por vírgula ou ponto e vírgula.', verbose_name='destinatários gerais')),
                ('assunto_queda', models.CharField(default='🔴 {sistema} fora do ar', max_length=200, verbose_name='assunto (queda)')),
                ('corpo_queda', models.TextField(default='Olá,\n\nO monitoramento da KS TEC identificou que o sistema {sistema} está fora do ar desde {inicio}.\nEndereço: {url}\nMotivo: {erro}\n\nNossa equipe já foi acionada e você receberá um novo aviso quando o serviço for restabelecido.\n\nKS TEC Soluções de Tecnologia', verbose_name='mensagem (queda)')),
                ('assunto_retorno', models.CharField(default='🟢 {sistema} restabelecido', max_length=200, verbose_name='assunto (retorno)')),
                ('corpo_retorno', models.TextField(default='Olá,\n\nO sistema {sistema} voltou a operar normalmente. Período de indisponibilidade: {duracao} (início em {inicio}).\n\nKS TEC Soluções de Tecnologia', verbose_name='mensagem (retorno)')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
            ],
            options={
                'verbose_name': 'configuração de alertas',
                'constraints': [models.UniqueConstraint(fields=('empresa',), name='config_alertas_empresa_unica')],
            },
        ),
        migrations.CreateModel(
            name='RelatorioSLA',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('competencia', models.DateField(verbose_name='competência')),
                ('versao', models.PositiveIntegerField(default=1, editable=False)),
                ('dados', models.JSONField(default=dict, editable=False)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADO', 'Aprovado')], default='RASCUNHO', editable=False, max_length=12)),
                ('aprovado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('aprovado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_sla', to='contratos.contrato')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('pdf', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.anexo')),
            ],
            options={
                'verbose_name': 'relatório de SLA',
                'verbose_name_plural': 'relatórios de SLA',
                'ordering': ['-competencia', '-versao'],
                'constraints': [models.UniqueConstraint(fields=('contrato', 'competencia', 'versao'), name='relatorio_sla_versao')],
            },
        ),
    ]
