# Generated by Django 5.2.18 on 2026-10-09 00:32

import apps.core.models
import apps.core.validadores
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "razao_social",
                    models.CharField(max_length=200, verbose_name="razão social"),
                ),
                ("nome_fantasia", models.CharField(blank=True, max_length=200)),
                (
                    "cnpj",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[apps.core.validadores.validar_cnpj],
                    ),
                ),
                (
                    "inscricao_municipal",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="inscrição municipal"
                    ),
                ),
                (
                    "inscricao_estadual",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="inscrição estadual"
                    ),
                ),
                (
                    "regime_tributario",
                    models.CharField(
                        choices=[
                            ("SIMPLES", "Simples Nacional"),
                            ("LUCRO_PRESUMIDO", "Lucro Presumido"),
                            ("LUCRO_REAL", "Lucro Real"),
                            ("MEI", "MEI"),
                        ],
                        default="SIMPLES",
                        max_length=20,
                        verbose_name="regime tributário",
                    ),
                ),
                (
                    "optante_simples",
                    models.BooleanField(
                        default=True, verbose_name="optante do Simples"
                    ),
                ),
                (
                    "regime_especial_tributacao",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "0 — Nenhum"),
                            (1, "1 — Microempresa municipal"),
                            (2, "2 — Estimativa"),
                            (3, "3 — Sociedade de profissionais"),
                            (4, "4 — Cooperativa"),
                            (5, "5 — MEI"),
                            (6, "6 — ME/EPP"),
                            (7, "7 — Profissional autônomo"),
                            (8, "8 — Notário ou registrador"),
                            (9, "9 — Outros"),
                        ],
                        default=0,
                        verbose_name="regime especial de tributação",
                    ),
                ),
                (
                    "natureza_juridica",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="natureza jurídica"
                    ),
                ),
                ("cnae_principal", models.CharField(blank=True, max_length=10)),
                ("cnaes_secundarios", models.JSONField(blank=True, default=list)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                ("site", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="publico/logos/"
                    ),
                ),
                ("cor_primaria", models.CharField(default="#0016E1", max_length=7)),
                (
                    "municipio_ibge",
                    models.CharField(
                        default="2932903",
                        max_length=7,
                        verbose_name="código IBGE do município",
                    ),
                ),
                (
                    "responsavel_tecnico",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="responsável técnico"
                    ),
                ),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
            },
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cep", models.CharField(max_length=9)),
                (
                    "tipo_logradouro",
                    models.CharField(blank=True, default="Rua", max_length=30),
                ),
                ("logradouro", models.CharField(max_length=200)),
                ("numero", models.CharField(blank=True, default="S/N", max_length=20)),
                ("complemento", models.CharField(blank=True, max_length=100)),
                ("bairro", models.CharField(max_length=100)),
                (
                    "municipio_ibge",
                    models.CharField(max_length=7, verbose_name="código IBGE"),
                ),
                (
                    "municipio_nome",
                    models.CharField(max_length=100, verbose_name="município"),
                ),
                ("uf", models.CharField(max_length=2)),
                ("pais_bacen", models.CharField(default="1058", max_length=4)),
            ],
            options={
                "verbose_name": "endereço",
                "verbose_name_plural": "endereços",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="e-mail"
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=150)),
                ("cpf", models.CharField(blank=True, max_length=11)),
                ("cargo", models.CharField(blank=True, max_length=100)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="publico/avatares/"
                    ),
                ),
                (
                    "tema",
                    models.CharField(
                        choices=[("claro", "Claro"), ("escuro", "Escuro")],
                        default="claro",
                        max_length=10,
                    ),
                ),
                ("mfa_ativo", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarios",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuário",
                "verbose_name_plural": "usuários",
            },
            managers=[
                ("objects", apps.core.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name="Anexo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "object_id",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                (
                    "arquivo",
                    models.FileField(
                        max_length=300, upload_to=apps.core.models._caminho_anexo
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("XML", "XML"),
                            ("PDF", "PDF"),
                            ("IMAGEM", "Imagem"),
                            ("PLANILHA", "Planilha"),
                            ("ZIP", "ZIP"),
                            ("DOCX", "DOCX"),
                            ("OUTRO", "Outro"),
                        ],
                        default="OUTRO",
                        max_length=10,
                    ),
                ),
                ("tamanho", models.PositiveBigIntegerField(default=0)),
                ("hash_sha256", models.CharField(blank=True, max_length=64)),
                ("descricao", models.CharField(blank=True, max_length=300)),
                (
                    "retencao_ate",
                    models.DateField(
                        blank=True,
                        help_text="Não pode ser excluído antes desta data.",
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "anexo",
                "verbose_name_plural": "anexos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="empresa",
            name="endereco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.endereco",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalAnexo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "object_id",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("arquivo", models.TextField(max_length=300)),
                ("nome", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("XML", "XML"),
                            ("PDF", "PDF"),
                            ("IMAGEM", "Imagem"),
                            ("PLANILHA", "Planilha"),
                            ("ZIP", "ZIP"),
                            ("DOCX", "DOCX"),
                            ("OUTRO", "Outro"),
                        ],
                        default="OUTRO",
                        max_length=10,
                    ),
                ),
                ("tamanho", models.PositiveBigIntegerField(default=0)),
                ("hash_sha256", models.CharField(blank=True, max_length=64)),
                ("descricao", models.CharField(blank=True, max_length=300)),
                (
                    "retencao_ate",
                    models.DateField(
                        blank=True,
                        help_text="Não pode ser excluído antes desta data.",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical anexo",
                "verbose_name_plural": "historical anexos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEmpresa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                (
                    "razao_social",
                    models.CharField(max_length=200, verbose_name="razão social"),
                ),
                ("nome_fantasia", models.CharField(blank=True, max_length=200)),
                (
                    "cnpj",
                    models.CharField(
                        db_index=True,
                        max_length=14,
                        validators=[apps.core.validadores.validar_cnpj],
                    ),
                ),
                (
                    "inscricao_municipal",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="inscrição municipal"
                    ),
                ),
                (
                    "inscricao_estadual",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="inscrição estadual"
                    ),
                ),
                (
                    "regime_tributario",
                    models.CharField(
                        choices=[
                            ("SIMPLES", "Simples Nacional"),
                            ("LUCRO_PRESUMIDO", "Lucro Presumido"),
                            ("LUCRO_REAL", "Lucro Real"),
                            ("MEI", "MEI"),
                        ],
                        default="SIMPLES",
                        max_length=20,
                        verbose_name="regime tributário",
                    ),
                ),
                (
                    "optante_simples",
                    models.BooleanField(
                        default=True, verbose_name="optante do Simples"
                    ),
                ),
                (
                    "regime_especial_tributacao",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "0 — Nenhum"),
                            (1, "1 — Microempresa municipal"),
                            (2, "2 — Estimativa"),
                            (3, "3 — Sociedade de profissionais"),
                            (4, "4 — Cooperativa"),
                            (5, "5 — MEI"),
                            (6, "6 — ME/EPP"),
                            (7, "7 — Profissional autônomo"),
                            (8, "8 — Notário ou registrador"),
                            (9, "9 — Outros"),
                        ],
                        default=0,
                        verbose_name="regime especial de tributação",
                    ),
                ),
                (
                    "natureza_juridica",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="natureza jurídica"
                    ),
                ),
                ("cnae_principal", models.CharField(blank=True, max_length=10)),
                ("cnaes_secundarios", models.JSONField(blank=True, default=list)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                ("site", models.URLField(blank=True)),
                ("logo", models.TextField(blank=True, max_length=100, null=True)),
                ("cor_primaria", models.CharField(default="#0016E1", max_length=7)),
                (
                    "municipio_ibge",
                    models.CharField(
                        default="2932903",
                        max_length=7,
                        verbose_name="código IBGE do município",
                    ),
                ),
                (
                    "responsavel_tecnico",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="responsável técnico"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.endereco",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical empresa",
                "verbose_name_plural": "historical empresas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEndereco",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("cep", models.CharField(max_length=9)),
                (
                    "tipo_logradouro",
                    models.CharField(blank=True, default="Rua", max_length=30),
                ),
                ("logradouro", models.CharField(max_length=200)),
                ("numero", models.CharField(blank=True, default="S/N", max_length=20)),
                ("complemento", models.CharField(blank=True, max_length=100)),
                ("bairro", models.CharField(max_length=100)),
                (
                    "municipio_ibge",
                    models.CharField(max_length=7, verbose_name="código IBGE"),
                ),
                (
                    "municipio_nome",
                    models.CharField(max_length=100, verbose_name="município"),
                ),
                ("uf", models.CharField(max_length=2)),
                ("pais_bacen", models.CharField(default="1058", max_length=4)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical endereço",
                "verbose_name_plural": "historical endereços",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalParametro",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                ("chave", models.CharField(max_length=100)),
                ("valor", models.JSONField(blank=True, default=dict)),
                ("descricao", models.CharField(blank=True, max_length=300)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical parâmetro",
                "verbose_name_plural": "historical parâmetros",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUsuario",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=150)),
                ("cpf", models.CharField(blank=True, max_length=11)),
                ("cargo", models.CharField(blank=True, max_length=100)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                ("avatar", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "tema",
                    models.CharField(
                        choices=[("claro", "Claro"), ("escuro", "Escuro")],
                        default="claro",
                        max_length=10,
                    ),
                ),
                ("mfa_ativo", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical usuário",
                "verbose_name_plural": "historical usuários",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LogAcesso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("acao", models.CharField(max_length=40)),
                ("object_id", models.CharField(blank=True, max_length=40)),
                ("descricao", models.CharField(blank=True, max_length=300)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "log de acesso",
                "verbose_name_plural": "logs de acesso",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="LogIntegracao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "servico",
                    models.CharField(
                        choices=[
                            ("SEFIN", "Sefin Nacional"),
                            ("ADN", "ADN Nacional"),
                            ("EL_ABRASF", "E&L ABRASF"),
                            ("EL_ACEITES", "E&L Aceites"),
                            ("GEMINI", "Gemini"),
                            ("BRASILAPI", "BrasilAPI"),
                            ("VIACEP", "ViaCEP"),
                            ("SLA", "Monitoramento"),
                            ("EMAIL", "E-mail"),
                        ],
                        max_length=12,
                    ),
                ),
                ("operacao", models.CharField(max_length=60)),
                (
                    "chave_idempotencia",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("request", models.TextField(blank=True)),
                ("response", models.TextField(blank=True)),
                (
                    "status_http",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("duracao_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("sucesso", models.BooleanField(default=False)),
                ("object_id", models.CharField(blank=True, max_length=40)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "log de integração",
                "verbose_name_plural": "logs de integração",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("titulo", models.CharField(max_length=200)),
                ("mensagem", models.TextField(blank=True)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("info", "Informação"),
                            ("success", "Sucesso"),
                            ("warning", "Atenção"),
                            ("danger", "Crítico"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("link", models.CharField(blank=True, max_length=300)),
                ("lida_em", models.DateTimeField(blank=True, null=True)),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("APP", "Aplicativo"),
                            ("EMAIL", "E-mail"),
                            ("WHATSAPP", "WhatsApp"),
                        ],
                        default="APP",
                        max_length=10,
                    ),
                ),
                (
                    "chave_dedup",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notificação",
                "verbose_name_plural": "notificações",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Segredo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=100)),
                ("valor_criptografado", models.BinaryField()),
                (
                    "escopo",
                    models.CharField(
                        choices=[
                            ("FISCAL", "Fiscal"),
                            ("IA", "IA"),
                            ("INTEGRACAO", "Integração"),
                        ],
                        default="INTEGRACAO",
                        max_length=12,
                    ),
                ),
                ("rotacionado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "segredo",
                "verbose_name_plural": "segredos",
            },
        ),
        migrations.CreateModel(
            name="Parametro",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("chave", models.CharField(max_length=100)),
                ("valor", models.JSONField(blank=True, default=dict)),
                ("descricao", models.CharField(blank=True, max_length=300)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "parâmetro",
                "verbose_name_plural": "parâmetros",
                "ordering": ["chave"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "chave"), name="parametro_unico_empresa"
                    )
                ],
            },
        ),
    ]
