# Generated by Django 5.2.18 on 2026-10-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintegracao',
            name='servico',
            field=models.CharField(choices=[('SEFIN', 'Sefin Nacional'), ('ADN', 'ADN Nacional'), ('EL_ABRASF', 'E&L ABRASF'), ('EL_ACEITES', 'E&L Aceites'), ('GEMINI', 'Gemini'), ('BRASILAPI', 'BrasilAPI'), ('VIACEP', 'ViaCEP'), ('SLA', 'Monitoramento'), ('EMAIL', 'E-mail'), ('ASAAS', 'Asaas'), ('WHATSAPP', 'WhatsApp')], max_length=12),
        ),
    ]
