# Generated by Django 5.2.18 on 2026-10-09 18:10

import django.db.models.deletion
import simple_history.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_logintegracao_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContaEmail',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('finalidade', models.CharField(choices=[('ALERTAS', 'Alertas e avisos do sistema'), ('DOCUMENTOS', 'Notas fiscais e documentos a clientes')], max_length=12)),
                ('nome_remetente', models.CharField(default='KS TEC', max_length=100, verbose_name='nome do remetente')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail remetente')),
                ('host', models.CharField(default='smtp.hostinger.com', max_length=150, verbose_name='servidor SMTP')),
                ('porta', models.PositiveIntegerField(default=465)),
                ('seguranca', models.CharField(choices=[('SSL', 'SSL/TLS implícito (porta 465)'), ('STARTTLS', 'STARTTLS (porta 587)')], default='SSL', max_length=10, verbose_name='segurança')),
                ('usuario', models.CharField(blank=True, help_text='Vazio usa o próprio e-mail.', max_length=150, verbose_name='usuário')),
                ('copia_para', models.EmailField(blank=True, help_text='Opcional: recebe uma cópia de cada envio.', max_length=254, verbose_name='cópia oculta para')),
                ('testado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ultimo_erro', models.CharField(blank=True, editable=False, max_length=300)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('senha', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.segredo')),
            ],
            options={
                'verbose_name': 'historical conta de e-mail',
                'verbose_name_plural': 'historical contas de e-mail',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ContaEmail',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('finalidade', models.CharField(choices=[('ALERTAS', 'Alertas e avisos do sistema'), ('DOCUMENTOS', 'Notas fiscais e documentos a clientes')], max_length=12)),
                ('nome_remetente', models.CharField(default='KS TEC', max_length=100, verbose_name='nome do remetente')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail remetente')),
                ('host', models.CharField(default='smtp.hostinger.com', max_length=150, verbose_name='servidor SMTP')),
                ('porta', models.PositiveIntegerField(default=465)),
                ('seguranca', models.CharField(choices=[('SSL', 'SSL/TLS implícito (porta 465)'), ('STARTTLS', 'STARTTLS (porta 587)')], default='SSL', max_length=10, verbose_name='segurança')),
                ('usuario', models.CharField(blank=True, help_text='Vazio usa o próprio e-mail.', max_length=150, verbose_name='usuário')),
                ('copia_para', models.EmailField(blank=True, help_text='Opcional: recebe uma cópia de cada envio.', max_length=254, verbose_name='cópia oculta para')),
                ('testado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ultimo_erro', models.CharField(blank=True, editable=False, max_length=300)),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('senha', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.segredo')),
            ],
            options={
                'verbose_name': 'conta de e-mail',
                'verbose_name_plural': 'contas de e-mail',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'finalidade'), name='conta_email_finalidade_unica')],
            },
        ),
    ]
