# Generated by Django 5.2.18 on 2026-10-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicalcontaemail_contaemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaemail',
            name='porta',
            field=models.PositiveIntegerField(default=587, help_text='Hetzner bloqueia a 465: use 587 com STARTTLS.'),
        ),
        migrations.AlterField(
            model_name='contaemail',
            name='seguranca',
            field=models.CharField(choices=[('SSL', 'SSL/TLS implícito (porta 465)'), ('STARTTLS', 'STARTTLS (porta 587)')], default='STARTTLS', max_length=10, verbose_name='segurança'),
        ),
        migrations.AlterField(
            model_name='historicalcontaemail',
            name='porta',
            field=models.PositiveIntegerField(default=587, help_text='Hetzner bloqueia a 465: use 587 com STARTTLS.'),
        ),
        migrations.AlterField(
            model_name='historicalcontaemail',
            name='seguranca',
            field=models.CharField(choices=[('SSL', 'SSL/TLS implícito (porta 465)'), ('STARTTLS', 'STARTTLS (porta 587)')], default='STARTTLS', max_length=10, verbose_name='segurança'),
        ),
    ]
