# Generated by Django 5.2.18 on 2026-10-09 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_historicalrecorrencia_recorrencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.contabancaria'),
        ),
    ]
