# Generated by Django 5.2.18 on 2026-10-09 04:44

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid6
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('core', '0002_contador'),
        ('financeiro', '0004_historicaltransacaoextrato_transacaoextrato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPlanilhaCustos',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('competencia', models.DateField(verbose_name='competência')),
                ('versao', models.PositiveIntegerField(default=1, editable=False)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADO', 'Aprovado')], default='RASCUNHO', editable=False, max_length=12)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações e fontes')),
                ('aprovado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('administracao_central', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Administração central (%)')),
                ('seguro_garantia', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Seguro/garantia (%)')),
                ('risco', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Risco (%)')),
                ('despesas_financeiras', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Despesas financeiras (%)')),
                ('lucro', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Lucro (%)')),
                ('tributos', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Tributos sobre faturamento (%)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aprovado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contratos.contrato')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pdf', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.anexo')),
                ('xlsx', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.anexo')),
            ],
            options={
                'verbose_name': 'historical planilha custos',
                'verbose_name_plural': 'historical planilha custoss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PlanilhaCustos',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('competencia', models.DateField(verbose_name='competência')),
                ('versao', models.PositiveIntegerField(default=1, editable=False)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADO', 'Aprovado')], default='RASCUNHO', editable=False, max_length=12)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações e fontes')),
                ('aprovado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('administracao_central', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Administração central (%)')),
                ('seguro_garantia', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Seguro/garantia (%)')),
                ('risco', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Risco (%)')),
                ('despesas_financeiras', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Despesas financeiras (%)')),
                ('lucro', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Lucro (%)')),
                ('tributos', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Tributos sobre faturamento (%)')),
                ('aprovado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planilhas_custos', to='contratos.contrato')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('pdf', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.anexo')),
                ('xlsx', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.anexo')),
            ],
            options={
                'ordering': ['-competencia', '-versao'],
            },
        ),
        migrations.CreateModel(
            name='ItemCusto',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('grupo', models.CharField(choices=[('MAO_DE_OBRA', 'Mão de obra'), ('INFRAESTRUTURA', 'Infraestrutura'), ('LICENCAS', 'Licenças e APIs'), ('INSUMOS', 'Insumos'), ('DESLOCAMENTO', 'Deslocamento'), ('INDIRETOS', 'Custos indiretos')], max_length=20)),
                ('descricao', models.CharField(max_length=250, verbose_name='descrição')),
                ('unidade', models.CharField(default='un', max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('rateio_pct', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(100)], verbose_name='rateio (%)')),
                ('periodicidade', models.CharField(choices=[('MENSAL', 'Mensal'), ('ANUAL', 'Anual / 12'), ('UNICO', 'Único nesta competência')], default='MENSAL', max_length=10)),
                ('fonte', models.CharField(max_length=250)),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('planilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.planilhacustos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalItemCusto',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('grupo', models.CharField(choices=[('MAO_DE_OBRA', 'Mão de obra'), ('INFRAESTRUTURA', 'Infraestrutura'), ('LICENCAS', 'Licenças e APIs'), ('INSUMOS', 'Insumos'), ('DESLOCAMENTO', 'Deslocamento'), ('INDIRETOS', 'Custos indiretos')], max_length=20)),
                ('descricao', models.CharField(max_length=250, verbose_name='descrição')),
                ('unidade', models.CharField(default='un', max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('rateio_pct', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(100)], verbose_name='rateio (%)')),
                ('periodicidade', models.CharField(choices=[('MENSAL', 'Mensal'), ('ANUAL', 'Anual / 12'), ('UNICO', 'Único nesta competência')], default='MENSAL', max_length=10)),
                ('fonte', models.CharField(max_length=250)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('planilha', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.planilhacustos')),
            ],
            options={
                'verbose_name': 'historical item custo',
                'verbose_name_plural': 'historical item custos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='planilhacustos',
            constraint=models.UniqueConstraint(fields=('contrato', 'competencia', 'versao'), name='planilha_custos_versao'),
        ),
    ]
