# Generated by Django 5.2.18 on 2026-10-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_historicalplanilhacustos_planilhacustos_itemcusto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocusto',
            name='ratear',
            field=models.BooleanField(default=True, help_text='Só para centros sem contrato (ex.: Administrativo, infraestrutura comum).', verbose_name='custo global rateado entre os contratos'),
        ),
        migrations.AddField(
            model_name='historicalcentrocusto',
            name='ratear',
            field=models.BooleanField(default=True, help_text='Só para centros sem contrato (ex.: Administrativo, infraestrutura comum).', verbose_name='custo global rateado entre os contratos'),
        ),
    ]
