# Generated by Django 5.2.18 on 2026-10-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicalcontaemail_contaemail'),
        ('mensageria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='assistente_ia',
            field=models.BooleanField(default=False, verbose_name='responder perguntas livres com IA (Gemini)'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='gemini_chave',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.segredo'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='modelo_ia',
            field=models.CharField(default='gemini-flash-latest', max_length=60, verbose_name='modelo Gemini'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='reiniciar_sessao',
            field=models.BooleanField(default=False, editable=False, help_text='Pedido da tela para o worker recriar a conexão (novo QR).'),
        ),
        migrations.AddField(
            model_name='confirmacao',
            name='dados',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaowhatsapp',
            name='assistente_ia',
            field=models.BooleanField(default=False, verbose_name='responder perguntas livres com IA (Gemini)'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaowhatsapp',
            name='gemini_chave',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.segredo'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaowhatsapp',
            name='modelo_ia',
            field=models.CharField(default='gemini-flash-latest', max_length=60, verbose_name='modelo Gemini'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaowhatsapp',
            name='reiniciar_sessao',
            field=models.BooleanField(default=False, editable=False, help_text='Pedido da tela para o worker recriar a conexão (novo QR).'),
        ),
    ]
