# Generated by Django 5.2.18 on 2026-10-09 00:37

import django.db.models.deletion
import simple_history.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certidao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="número / código de controle",
                    ),
                ),
                ("data_emissao", models.DateField(verbose_name="data de emissão")),
                ("data_validade", models.DateField(verbose_name="data de validade")),
                ("arquivo", models.FileField(blank=True, upload_to="certidoes/%Y/")),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("NEGATIVA", "Negativa"),
                            (
                                "POSITIVA_COM_EFEITO_NEGATIVA",
                                "Positiva com efeito de negativa",
                            ),
                            ("POSITIVA", "Positiva"),
                        ],
                        default="NEGATIVA",
                        max_length=30,
                        verbose_name="situação",
                    ),
                ),
                (
                    "codigo_autenticidade",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="código de autenticidade",
                    ),
                ),
                (
                    "url_validacao",
                    models.URLField(blank=True, verbose_name="URL de validação"),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="observação")),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "certidão",
                "verbose_name_plural": "certidões",
                "ordering": ["-data_validade"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalKitHabilitacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "nome",
                    models.CharField(
                        help_text='Ex.: "Dispensa 012/2026 — Prefeitura X"',
                        max_length=200,
                    ),
                ),
                (
                    "gerado_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zip",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.anexo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical kit de habilitação",
                "verbose_name_plural": "historical kits de habilitação",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTipoCertidao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=150)),
                (
                    "orgao_emissor",
                    models.CharField(max_length=150, verbose_name="órgão emissor"),
                ),
                (
                    "esfera",
                    models.CharField(
                        choices=[
                            ("FEDERAL", "Federal"),
                            ("ESTADUAL", "Estadual"),
                            ("MUNICIPAL", "Municipal"),
                            ("TRABALHISTA", "Trabalhista"),
                            ("JUDICIAL", "Judicial"),
                            ("OUTRA", "Outra"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "url_emissao",
                    models.URLField(blank=True, verbose_name="URL de emissão"),
                ),
                (
                    "validade_padrao_dias",
                    models.PositiveSmallIntegerField(
                        default=180, verbose_name="validade padrão (dias)"
                    ),
                ),
                (
                    "obrigatoria_habilitacao",
                    models.BooleanField(
                        default=True, verbose_name="obrigatória para habilitação"
                    ),
                ),
                ("instrucoes", models.TextField(blank=True, verbose_name="instruções")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical tipo de certidão",
                "verbose_name_plural": "historical tipos de certidão",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="KitHabilitacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "nome",
                    models.CharField(
                        help_text='Ex.: "Dispensa 012/2026 — Prefeitura X"',
                        max_length=200,
                    ),
                ),
                (
                    "gerado_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "certidoes",
                    models.ManyToManyField(
                        blank=True, related_name="kits", to="certidoes.certidao"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documentos_extra",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Contrato social, cartão CNPJ, atestados…",
                        related_name="+",
                        to="core.anexo",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "zip",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.anexo",
                    ),
                ),
            ],
            options={
                "verbose_name": "kit de habilitação",
                "verbose_name_plural": "kits de habilitação",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="TipoCertidao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=150)),
                (
                    "orgao_emissor",
                    models.CharField(max_length=150, verbose_name="órgão emissor"),
                ),
                (
                    "esfera",
                    models.CharField(
                        choices=[
                            ("FEDERAL", "Federal"),
                            ("ESTADUAL", "Estadual"),
                            ("MUNICIPAL", "Municipal"),
                            ("TRABALHISTA", "Trabalhista"),
                            ("JUDICIAL", "Judicial"),
                            ("OUTRA", "Outra"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "url_emissao",
                    models.URLField(blank=True, verbose_name="URL de emissão"),
                ),
                (
                    "validade_padrao_dias",
                    models.PositiveSmallIntegerField(
                        default=180, verbose_name="validade padrão (dias)"
                    ),
                ),
                (
                    "obrigatoria_habilitacao",
                    models.BooleanField(
                        default=True, verbose_name="obrigatória para habilitação"
                    ),
                ),
                ("instrucoes", models.TextField(blank=True, verbose_name="instruções")),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de certidão",
                "verbose_name_plural": "tipos de certidão",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCertidao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="número / código de controle",
                    ),
                ),
                ("data_emissao", models.DateField(verbose_name="data de emissão")),
                ("data_validade", models.DateField(verbose_name="data de validade")),
                ("arquivo", models.TextField(blank=True, max_length=100)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("NEGATIVA", "Negativa"),
                            (
                                "POSITIVA_COM_EFEITO_NEGATIVA",
                                "Positiva com efeito de negativa",
                            ),
                            ("POSITIVA", "Positiva"),
                        ],
                        default="NEGATIVA",
                        max_length=30,
                        verbose_name="situação",
                    ),
                ),
                (
                    "codigo_autenticidade",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="código de autenticidade",
                    ),
                ),
                (
                    "url_validacao",
                    models.URLField(blank=True, verbose_name="URL de validação"),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="observação")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="certidoes.tipocertidao",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical certidão",
                "verbose_name_plural": "historical certidões",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="certidao",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certidoes",
                to="certidoes.tipocertidao",
            ),
        ),
    ]
