# Generated by Django 5.2.18 on 2026-10-09 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='perfil_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='servico_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='tomador_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='perfil_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='servico_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='tomador_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='contratos.contrato'),
        ),
    ]
