# Generated by Django 5.2.18 on 2026-10-09 04:00

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_historicalpessoa_cnae_principal_and_more'),
        ('catalogo', '0003_servicomunicipal'),
        ('contratos', '0001_initial'),
        ('core', '0002_contador'),
        ('financeiro', '0003_alter_lancamento_conta_bancaria'),
        ('fiscal', '0002_historicalnotafiscal_perfil_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoDigital',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=150)),
                ('cnpj', models.CharField(editable=False, max_length=14)),
                ('validade_inicio', models.DateTimeField(editable=False)),
                ('validade_fim', models.DateTimeField(editable=False)),
                ('impressao_sha256', models.CharField(editable=False, max_length=64)),
                ('arquivo_criptografado', models.BinaryField()),
                ('senha_criptografada', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('canal_padrao', models.CharField(choices=[('MUNICIPAL_EL', 'Municipal E&L — DPS nacional'), ('NACIONAL', 'Emissor público nacional')], default='MUNICIPAL_EL', max_length=20)),
                ('ambiente', models.PositiveSmallIntegerField(choices=[(2, 'Homologação'), (1, 'Produção')], default=2)),
                ('serie_dps', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(79999)])),
                ('aliquota_iss', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ISS padrão (%)')),
                ('total_tributos_simples', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tributos totais aproximados do Simples (%)')),
                ('vigencia_inicio', models.DateField(blank=True, null=True)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('fonte_tributacao', models.CharField(blank=True, max_length=300)),
                ('prazo_recebimento_dias', models.PositiveIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(365)])),
                ('emissao_nacional_habilitada', models.BooleanField(default=False, editable=False)),
                ('ultima_verificacao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('diagnostico', models.JSONField(blank=True, default=dict, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCertificadoDigital',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=150)),
                ('cnpj', models.CharField(editable=False, max_length=14)),
                ('validade_inicio', models.DateTimeField(editable=False)),
                ('validade_fim', models.DateTimeField(editable=False)),
                ('impressao_sha256', models.CharField(editable=False, max_length=64)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical certificado digital',
                'verbose_name_plural': 'historical certificado digitals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalConfiguracaoFiscal',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('canal_padrao', models.CharField(choices=[('MUNICIPAL_EL', 'Municipal E&L — DPS nacional'), ('NACIONAL', 'Emissor público nacional')], default='MUNICIPAL_EL', max_length=20)),
                ('ambiente', models.PositiveSmallIntegerField(choices=[(2, 'Homologação'), (1, 'Produção')], default=2)),
                ('serie_dps', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(79999)])),
                ('aliquota_iss', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ISS padrão (%)')),
                ('total_tributos_simples', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tributos totais aproximados do Simples (%)')),
                ('vigencia_inicio', models.DateField(blank=True, null=True)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('fonte_tributacao', models.CharField(blank=True, max_length=300)),
                ('prazo_recebimento_dias', models.PositiveIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(365)])),
                ('emissao_nacional_habilitada', models.BooleanField(default=False, editable=False)),
                ('ultima_verificacao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('diagnostico', models.JSONField(blank=True, default=dict, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical configuracao fiscal',
                'verbose_name_plural': 'historical configuracao fiscals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSequenciaNumeracao',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ambiente', models.PositiveSmallIntegerField()),
                ('serie', models.PositiveIntegerField()),
                ('ultimo_numero', models.PositiveBigIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical sequencia numeracao',
                'verbose_name_plural': 'historical sequencia numeracaos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTentativaTransmissao',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('canal', models.CharField(choices=[('MUNICIPAL_EL', 'Municipal E&L — DPS nacional'), ('NACIONAL', 'Emissor público nacional')], max_length=20)),
                ('ambiente', models.PositiveSmallIntegerField()),
                ('id_dps', models.CharField(max_length=45)),
                ('situacao', models.CharField(default='PREPARADA', max_length=50)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resposta', models.JSONField(blank=True, default=dict)),
                ('consultas', models.JSONField(blank=True, default=list)),
                ('hash_requisicao', models.CharField(max_length=64)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical tentativa transmissao',
                'verbose_name_plural': 'historical tentativa transmissaos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SequenciaNumeracao',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ambiente', models.PositiveSmallIntegerField()),
                ('serie', models.PositiveIntegerField()),
                ('ultimo_numero', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TentativaTransmissao',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('canal', models.CharField(choices=[('MUNICIPAL_EL', 'Municipal E&L — DPS nacional'), ('NACIONAL', 'Emissor público nacional')], max_length=20)),
                ('ambiente', models.PositiveSmallIntegerField()),
                ('id_dps', models.CharField(max_length=45)),
                ('situacao', models.CharField(default='PREPARADA', max_length=50)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resposta', models.JSONField(blank=True, default=dict)),
                ('consultas', models.JSONField(blank=True, default=list)),
                ('hash_requisicao', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterModelOptions(
            name='historicalnotafiscal',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical NFS-e', 'verbose_name_plural': 'historical NFS-e'},
        ),
        migrations.AlterModelOptions(
            name='notafiscal',
            options={'ordering': ['-criado_em'], 'verbose_name': 'NFS-e', 'verbose_name_plural': 'NFS-e'},
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='ambiente',
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='autorizada_em',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='canal',
            field=models.CharField(blank=True, choices=[('MUNICIPAL_EL', 'Municipal E&L — DPS nacional'), ('NACIONAL', 'Emissor público nacional')], editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='chave_acesso',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='emissao_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='id_dps',
            field=models.CharField(blank=True, editable=False, max_length=45),
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='numero_nfse',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='vencimento_recebivel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='xml_autorizado',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.anexo'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='ambiente',
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='autorizada_em',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='canal',
            field=models.CharField(blank=True, choices=[('MUNICIPAL_EL', 'Municipal E&L — DPS nacional'), ('NACIONAL', 'Emissor público nacional')], editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='chave_acesso',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='emissao_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='id_dps',
            field=models.CharField(blank=True, editable=False, max_length=45),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='numero_nfse',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='vencimento_recebivel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='xml_autorizado',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.anexo'),
        ),
        migrations.AlterField(
            model_name='historicalnotafiscal',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('TRANSMITINDO', 'Transmitindo'), ('EM_PROCESSAMENTO', 'Em processamento'), ('AUTORIZADA', 'Autorizada'), ('REJEITADA', 'Rejeitada'), ('ERRO_COMUNICACAO', 'Resultado pendente de consulta'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('TRANSMITINDO', 'Transmitindo'), ('EM_PROCESSAMENTO', 'Em processamento'), ('AUTORIZADA', 'Autorizada'), ('REJEITADA', 'Rejeitada'), ('ERRO_COMUNICACAO', 'Resultado pendente de consulta'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', editable=False, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.UniqueConstraint(condition=models.Q(('chave_acesso', ''), _negated=True), fields=('empresa', 'ambiente', 'chave_acesso'), name='nfse_chave_unica'),
        ),
        migrations.AddField(
            model_name='certificadodigital',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificadodigital',
            name='empresa',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='certificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.certificadodigital'),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='conta_recebimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='empresa',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='perfil_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.perfilfiscal'),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='token_municipal',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.segredo'),
        ),
        migrations.AddField(
            model_name='historicalcertificadodigital',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcertificadodigital',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='historicalcertificadodigital',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaofiscal',
            name='certificado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fiscal.certificadodigital'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaofiscal',
            name='conta_recebimento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaofiscal',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaofiscal',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaofiscal',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaofiscal',
            name='perfil_padrao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fiscal.perfilfiscal'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaofiscal',
            name='token_municipal',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.segredo'),
        ),
        migrations.AddField(
            model_name='historicalsequencianumeracao',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsequencianumeracao',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='historicalsequencianumeracao',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltentativatransmissao',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltentativatransmissao',
            name='dps_assinada',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.anexo'),
        ),
        migrations.AddField(
            model_name='historicaltentativatransmissao',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='historicaltentativatransmissao',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltentativatransmissao',
            name='nota',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fiscal.notafiscal'),
        ),
        migrations.AddField(
            model_name='sequencianumeracao',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sequencianumeracao',
            name='empresa',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='tentativatransmissao',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tentativatransmissao',
            name='dps_assinada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.anexo'),
        ),
        migrations.AddField(
            model_name='tentativatransmissao',
            name='empresa',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='tentativatransmissao',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tentativas', to='fiscal.notafiscal'),
        ),
        migrations.AddConstraint(
            model_name='configuracaofiscal',
            constraint=models.UniqueConstraint(fields=('empresa',), name='config_fiscal_empresa_unica'),
        ),
        migrations.AddConstraint(
            model_name='sequencianumeracao',
            constraint=models.UniqueConstraint(fields=('empresa', 'ambiente', 'serie'), name='sequencia_dps_unica'),
        ),
        migrations.AddConstraint(
            model_name='tentativatransmissao',
            constraint=models.UniqueConstraint(fields=('nota', 'canal'), name='tentativa_nota_canal_unica'),
        ),
    ]
