# Generated by Django 5.2.18 on 2026-10-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_certificadodigital_configuracaofiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnotafiscal',
            name='ambiente',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnotafiscal',
            name='autorizada_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='ambiente',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='autorizada_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
