# Generated by Django 5.2.18 on 2026-10-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_alter_historicalnotafiscal_ambiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnotafiscal',
            name='ambiente',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Produção'), (2, 'Homologação')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='ambiente',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Produção'), (2, 'Homologação')], editable=False, null=True),
        ),
    ]
