# Generated by Django 5.2.18 on 2026-10-09 04:44

import django.db.models.deletion
import simple_history.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contador'),
        ('fiscal', '0005_alter_historicalnotafiscal_ambiente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='pdf',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.anexo'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='pdf',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.anexo'),
        ),
        migrations.CreateModel(
            name='EntregaNota',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('destinatarios', models.JSONField(default=list)),
                ('assunto', models.CharField(max_length=200)),
                ('mensagem', models.TextField(max_length=10000)),
                ('manifesto', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PREPARADA', 'Preparada para revisão'), ('ENVIANDO', 'Envio iniciado'), ('ENVIADA', 'Aceita pelo servidor de e-mail'), ('SIMULADA', 'Simulada no ambiente local'), ('INCERTA', 'Resultado do envio inconclusivo')], default='PREPARADA', editable=False, max_length=15)),
                ('enviado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='fiscal.notafiscal')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.anexo')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEntregaNota',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('destinatarios', models.JSONField(default=list)),
                ('assunto', models.CharField(max_length=200)),
                ('mensagem', models.TextField(max_length=10000)),
                ('manifesto', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PREPARADA', 'Preparada para revisão'), ('ENVIANDO', 'Envio iniciado'), ('ENVIADA', 'Aceita pelo servidor de e-mail'), ('SIMULADA', 'Simulada no ambiente local'), ('INCERTA', 'Resultado do envio inconclusivo')], default='PREPARADA', editable=False, max_length=15)),
                ('enviado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nota', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fiscal.notafiscal')),
                ('pacote', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.anexo')),
            ],
            options={
                'verbose_name': 'historical entrega nota',
                'verbose_name_plural': 'historical entrega notas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
