# Generated by Django 5.2.18 on 2026-10-09 00:44

import django.db.models.deletion
import simple_history.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_contador"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoNBS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="9 dígitos, sem máscara",
                        max_length=9,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                ("codigo_mascarado", models.CharField(max_length=14)),
                ("descricao", models.TextField(verbose_name="descrição")),
            ],
            options={
                "verbose_name": "código NBS",
                "verbose_name_plural": "códigos NBS",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="CodigoServicoLC116",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        help_text='Ex.: "01.07"', max_length=5, unique=True
                    ),
                ),
                ("descricao", models.TextField(verbose_name="descrição")),
            ],
            options={
                "verbose_name": "item da LC 116",
                "verbose_name_plural": "itens da LC 116",
                "ordering": ["item"],
            },
        ),
        migrations.CreateModel(
            name="CodigoTributacaoNacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="6 dígitos, sem máscara (ex.: 010701)",
                        max_length=6,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                ("item", models.CharField(max_length=2)),
                ("subitem", models.CharField(max_length=2)),
                ("desdobro", models.CharField(default="01", max_length=2)),
                ("descricao", models.TextField(verbose_name="descrição")),
            ],
            options={
                "verbose_name": "código de tributação nacional",
                "verbose_name_plural": "códigos de tributação nacional",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="CorrelacaoNBS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_lc116", models.CharField(db_index=True, max_length=5)),
                ("nbs", models.CharField(db_index=True, max_length=9)),
                ("descricao_nbs", models.TextField(blank=True)),
                ("ps_onerosa", models.CharField(blank=True, max_length=10)),
                ("adq_exterior", models.CharField(blank=True, max_length=10)),
                ("ind_op", models.CharField(blank=True, max_length=10)),
                ("local_incidencia_ibs", models.CharField(blank=True, max_length=200)),
                ("c_class_trib", models.CharField(blank=True, max_length=10)),
                ("nome_c_class_trib", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name": "correlação NBS (IBS/CBS)",
                "verbose_name_plural": "correlações NBS (IBS/CBS)",
                "ordering": ["item_lc116", "nbs"],
            },
        ),
        migrations.CreateModel(
            name="CategoriaCatalogo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SERVICO_TI", "Serviço de TI"),
                            ("SERVICO_GRAFICO", "Serviço gráfico"),
                            ("PRODUTO_GRAFICO", "Produto gráfico"),
                            ("AUDIOVISUAL", "Audiovisual"),
                            ("SOCIAL_MEDIA", "Social media"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        default="package", max_length=30, verbose_name="ícone"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCategoriaCatalogo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SERVICO_TI", "Serviço de TI"),
                            ("SERVICO_GRAFICO", "Serviço gráfico"),
                            ("PRODUTO_GRAFICO", "Produto gráfico"),
                            ("AUDIOVISUAL", "Audiovisual"),
                            ("SOCIAL_MEDIA", "Social media"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        default="package", max_length=30, verbose_name="ícone"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical categoria",
                "verbose_name_plural": "historical categorias",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalItemCatalogo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "codigo_interno",
                    models.CharField(
                        max_length=30, verbose_name="código interno (SKU)"
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "natureza",
                    models.CharField(
                        choices=[
                            ("SERVICO", "Serviço"),
                            ("PRODUTO", "Produto (mercadoria)"),
                        ],
                        default="SERVICO",
                        max_length=10,
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        choices=[
                            ("UN", "Unidade"),
                            ("HORA", "Hora"),
                            ("MES", "Mês"),
                            ("MILHEIRO", "Milheiro"),
                            ("M2", "m²"),
                            ("PACOTE", "Pacote"),
                            ("DIARIA", "Diária"),
                        ],
                        default="UN",
                        max_length=10,
                    ),
                ),
                (
                    "preco_base",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="preço base"
                    ),
                ),
                (
                    "custo_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="custo base",
                    ),
                ),
                (
                    "margem_alvo_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="margem alvo (%)",
                    ),
                ),
                (
                    "codigo_tributacao_municipal",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="código de tributação municipal",
                    ),
                ),
                (
                    "cnae",
                    models.CharField(blank=True, max_length=10, verbose_name="CNAE"),
                ),
                (
                    "aliquota_iss_padrao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="alíquota de ISS padrão (%)",
                    ),
                ),
                (
                    "ncm",
                    models.CharField(
                        blank=True,
                        help_text="Somente produtos.",
                        max_length=10,
                        verbose_name="NCM",
                    ),
                ),
                (
                    "prazo_entrega_dias",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="prazo de entrega (dias)"
                    ),
                ),
                ("permite_venda_avulsa", models.BooleanField(default=True)),
                ("imagem", models.TextField(blank=True, max_length=100, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogo.categoriacatalogo",
                    ),
                ),
                (
                    "codigo_tributacao_nacional",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogo.codigotributacaonacional",
                        verbose_name="código de tributação nacional",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item_lc116",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogo.codigoservicolc116",
                        verbose_name="item LC 116",
                    ),
                ),
                (
                    "nbs",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogo.codigonbs",
                        verbose_name="NBS",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical item do catálogo",
                "verbose_name_plural": "historical catálogo",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ItemCatalogo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "codigo_interno",
                    models.CharField(
                        max_length=30, verbose_name="código interno (SKU)"
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "natureza",
                    models.CharField(
                        choices=[
                            ("SERVICO", "Serviço"),
                            ("PRODUTO", "Produto (mercadoria)"),
                        ],
                        default="SERVICO",
                        max_length=10,
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        choices=[
                            ("UN", "Unidade"),
                            ("HORA", "Hora"),
                            ("MES", "Mês"),
                            ("MILHEIRO", "Milheiro"),
                            ("M2", "m²"),
                            ("PACOTE", "Pacote"),
                            ("DIARIA", "Diária"),
                        ],
                        default="UN",
                        max_length=10,
                    ),
                ),
                (
                    "preco_base",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="preço base"
                    ),
                ),
                (
                    "custo_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="custo base",
                    ),
                ),
                (
                    "margem_alvo_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="margem alvo (%)",
                    ),
                ),
                (
                    "codigo_tributacao_municipal",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="código de tributação municipal",
                    ),
                ),
                (
                    "cnae",
                    models.CharField(blank=True, max_length=10, verbose_name="CNAE"),
                ),
                (
                    "aliquota_iss_padrao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="alíquota de ISS padrão (%)",
                    ),
                ),
                (
                    "ncm",
                    models.CharField(
                        blank=True,
                        help_text="Somente produtos.",
                        max_length=10,
                        verbose_name="NCM",
                    ),
                ),
                (
                    "prazo_entrega_dias",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="prazo de entrega (dias)"
                    ),
                ),
                ("permite_venda_avulsa", models.BooleanField(default=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="catalogo/"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itens",
                        to="catalogo.categoriacatalogo",
                    ),
                ),
                (
                    "codigo_tributacao_nacional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.codigotributacaonacional",
                        verbose_name="código de tributação nacional",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "item_lc116",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.codigoservicolc116",
                        verbose_name="item LC 116",
                    ),
                ),
                (
                    "nbs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.codigonbs",
                        verbose_name="NBS",
                    ),
                ),
            ],
            options={
                "verbose_name": "item do catálogo",
                "verbose_name_plural": "catálogo",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalVariacaoGrafica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "atributo",
                    models.CharField(
                        choices=[
                            ("FORMATO", "Formato"),
                            ("PAPEL", "Papel"),
                            ("GRAMATURA", "Gramatura"),
                            ("CORES", "Cores"),
                            ("ACABAMENTO", "Acabamento"),
                            ("LAMINACAO", "Laminação"),
                            ("CORTE", "Corte"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "opcao",
                    models.CharField(
                        help_text='Ex.: "A4", "Couché 150g", "4x4"',
                        max_length=80,
                        verbose_name="opção",
                    ),
                ),
                (
                    "acrescimo_tipo",
                    models.CharField(
                        choices=[
                            ("FIXO", "Valor fixo (rateado na quantidade)"),
                            ("PERCENTUAL", "Percentual sobre o unitário"),
                            ("POR_UNIDADE", "Valor por unidade"),
                        ],
                        default="POR_UNIDADE",
                        max_length=12,
                        verbose_name="tipo de acréscimo",
                    ),
                ),
                (
                    "acrescimo_valor",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        verbose_name="acréscimo",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogo.itemcatalogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical variação gráfica",
                "verbose_name_plural": "historical variações gráficas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFaixaPreco",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "quantidade_min",
                    models.PositiveIntegerField(verbose_name="quantidade mínima"),
                ),
                (
                    "quantidade_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="quantidade máxima"
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="preço unitário"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogo.itemcatalogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical faixa de preço",
                "verbose_name_plural": "historical faixas de preço",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="FaixaPreco",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "quantidade_min",
                    models.PositiveIntegerField(verbose_name="quantidade mínima"),
                ),
                (
                    "quantidade_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="quantidade máxima"
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="preço unitário"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faixas",
                        to="catalogo.itemcatalogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "faixa de preço",
                "verbose_name_plural": "faixas de preço",
                "ordering": ["item", "quantidade_min"],
            },
        ),
        migrations.CreateModel(
            name="VariacaoGrafica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "atributo",
                    models.CharField(
                        choices=[
                            ("FORMATO", "Formato"),
                            ("PAPEL", "Papel"),
                            ("GRAMATURA", "Gramatura"),
                            ("CORES", "Cores"),
                            ("ACABAMENTO", "Acabamento"),
                            ("LAMINACAO", "Laminação"),
                            ("CORTE", "Corte"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "opcao",
                    models.CharField(
                        help_text='Ex.: "A4", "Couché 150g", "4x4"',
                        max_length=80,
                        verbose_name="opção",
                    ),
                ),
                (
                    "acrescimo_tipo",
                    models.CharField(
                        choices=[
                            ("FIXO", "Valor fixo (rateado na quantidade)"),
                            ("PERCENTUAL", "Percentual sobre o unitário"),
                            ("POR_UNIDADE", "Valor por unidade"),
                        ],
                        default="POR_UNIDADE",
                        max_length=12,
                        verbose_name="tipo de acréscimo",
                    ),
                ),
                (
                    "acrescimo_valor",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        verbose_name="acréscimo",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variacoes",
                        to="catalogo.itemcatalogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "variação gráfica",
                "verbose_name_plural": "variações gráficas",
                "ordering": ["atributo", "opcao"],
            },
        ),
        migrations.AddConstraint(
            model_name="itemcatalogo",
            constraint=models.UniqueConstraint(
                fields=("empresa", "codigo_interno"), name="sku_unico"
            ),
        ),
    ]
