# Generated by Django 5.2.18 on 2026-10-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigotributacaonacional',
            name='vigente',
            field=models.BooleanField(default=True, help_text='Disponível na última lista oficial importada.'),
        ),
    ]
