# Generated by Django 5.2.18 on 2026-10-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_codigotributacaonacional_vigente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio_ibge', models.CharField(max_length=7)),
                ('item_lc116', models.CharField(max_length=5)),
                ('descricao', models.TextField()),
                ('codigo_integracao', models.CharField(blank=True, max_length=20)),
                ('fonte', models.URLField(max_length=500)),
                ('codigo_confirmado', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['item_lc116'],
                'constraints': [models.UniqueConstraint(fields=('municipio_ibge', 'item_lc116'), name='servico_municipal_unico')],
            },
        ),
    ]
