# Generated by Django 5.2.18 on 2026-10-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendafaturamento',
            name='discriminacao',
            field=models.TextField(blank=True, help_text='Placeholders: {competencia}, {mes_nome}, {ano}, {parcela}, {parcela2}, {total_parcelas}, {valor}, {contrato}, {empenho}, {objeto}.', max_length=2000, verbose_name='modelo da discriminação'),
        ),
        migrations.AlterField(
            model_name='historicalagendafaturamento',
            name='discriminacao',
            field=models.TextField(blank=True, help_text='Placeholders: {competencia}, {mes_nome}, {ano}, {parcela}, {parcela2}, {total_parcelas}, {valor}, {contrato}, {empenho}, {objeto}.', max_length=2000, verbose_name='modelo da discriminação'),
        ),
    ]
