# Generated by Django 5.2.18 on 2026-10-09 00:32

import apps.core.validadores
import simple_history.models
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=150)),
                (
                    "cargo",
                    models.CharField(
                        blank=True,
                        help_text='Ex.: "Fiscal do contrato", "Gestor", "Financeiro"',
                        max_length=100,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                ("recebe_relatorios", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "contato",
                "verbose_name_plural": "contatos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalContato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=150)),
                (
                    "cargo",
                    models.CharField(
                        blank=True,
                        help_text='Ex.: "Fiscal do contrato", "Gestor", "Financeiro"',
                        max_length=100,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                ("recebe_relatorios", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical contato",
                "verbose_name_plural": "historical contatos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPessoa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("F", "Pessoa física"), ("J", "Pessoa jurídica")],
                        default="J",
                        max_length=1,
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        max_length=14,
                        validators=[apps.core.validadores.validar_cpf_cnpj],
                        verbose_name="CPF/CNPJ",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(
                        max_length=200, verbose_name="razão social / nome"
                    ),
                ),
                ("nome_fantasia", models.CharField(blank=True, max_length=200)),
                (
                    "inscricao_municipal",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="inscrição municipal"
                    ),
                ),
                (
                    "inscricao_estadual",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="inscrição estadual"
                    ),
                ),
                (
                    "e_orgao_publico",
                    models.BooleanField(default=False, verbose_name="é órgão público"),
                ),
                (
                    "esfera",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MUNICIPAL", "Municipal"),
                            ("ESTADUAL", "Estadual"),
                            ("FEDERAL", "Federal"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "email_nf",
                    models.EmailField(
                        blank=True,
                        help_text="Destino do envio automático da nota.",
                        max_length=254,
                        verbose_name="e-mail para NF",
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=30)),
                (
                    "eh_cliente",
                    models.BooleanField(default=True, verbose_name="cliente"),
                ),
                (
                    "eh_fornecedor",
                    models.BooleanField(default=False, verbose_name="fornecedor"),
                ),
                (
                    "optante_simples",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="optante do Simples"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "finalidade_dados",
                    models.CharField(
                        blank=True,
                        default="Execução de contrato e obrigações fiscais",
                        max_length=200,
                        verbose_name="finalidade do tratamento (LGPD)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pessoa",
                "verbose_name_plural": "historical clientes e fornecedores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("F", "Pessoa física"), ("J", "Pessoa jurídica")],
                        default="J",
                        max_length=1,
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        max_length=14,
                        validators=[apps.core.validadores.validar_cpf_cnpj],
                        verbose_name="CPF/CNPJ",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(
                        max_length=200, verbose_name="razão social / nome"
                    ),
                ),
                ("nome_fantasia", models.CharField(blank=True, max_length=200)),
                (
                    "inscricao_municipal",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="inscrição municipal"
                    ),
                ),
                (
                    "inscricao_estadual",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="inscrição estadual"
                    ),
                ),
                (
                    "e_orgao_publico",
                    models.BooleanField(default=False, verbose_name="é órgão público"),
                ),
                (
                    "esfera",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MUNICIPAL", "Municipal"),
                            ("ESTADUAL", "Estadual"),
                            ("FEDERAL", "Federal"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "email_nf",
                    models.EmailField(
                        blank=True,
                        help_text="Destino do envio automático da nota.",
                        max_length=254,
                        verbose_name="e-mail para NF",
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=30)),
                (
                    "eh_cliente",
                    models.BooleanField(default=True, verbose_name="cliente"),
                ),
                (
                    "eh_fornecedor",
                    models.BooleanField(default=False, verbose_name="fornecedor"),
                ),
                (
                    "optante_simples",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="optante do Simples"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "finalidade_dados",
                    models.CharField(
                        blank=True,
                        default="Execução de contrato e obrigações fiscais",
                        max_length=200,
                        verbose_name="finalidade do tratamento (LGPD)",
                    ),
                ),
            ],
            options={
                "verbose_name": "pessoa",
                "verbose_name_plural": "clientes e fornecedores",
                "ordering": ["razao_social"],
            },
        ),
    ]
