# Generated by Django 5.2.18 on 2026-10-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpessoa',
            name='cnae_principal',
            field=models.CharField(blank=True, max_length=10, verbose_name='CNAE principal'),
        ),
        migrations.AddField(
            model_name='historicalpessoa',
            name='data_abertura',
            field=models.DateField(blank=True, null=True, verbose_name='data de abertura'),
        ),
        migrations.AddField(
            model_name='historicalpessoa',
            name='descricao_cnae',
            field=models.CharField(blank=True, max_length=300, verbose_name='descrição do CNAE'),
        ),
        migrations.AddField(
            model_name='historicalpessoa',
            name='natureza_juridica',
            field=models.CharField(blank=True, max_length=200, verbose_name='natureza jurídica'),
        ),
        migrations.AddField(
            model_name='historicalpessoa',
            name='porte',
            field=models.CharField(blank=True, max_length=100, verbose_name='porte da empresa'),
        ),
        migrations.AddField(
            model_name='historicalpessoa',
            name='situacao_cadastral',
            field=models.CharField(blank=True, max_length=100, verbose_name='situação cadastral'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cnae_principal',
            field=models.CharField(blank=True, max_length=10, verbose_name='CNAE principal'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_abertura',
            field=models.DateField(blank=True, null=True, verbose_name='data de abertura'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='descricao_cnae',
            field=models.CharField(blank=True, max_length=300, verbose_name='descrição do CNAE'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='natureza_juridica',
            field=models.CharField(blank=True, max_length=200, verbose_name='natureza jurídica'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='porte',
            field=models.CharField(blank=True, max_length=100, verbose_name='porte da empresa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='situacao_cadastral',
            field=models.CharField(blank=True, max_length=100, verbose_name='situação cadastral'),
        ),
    ]
