# Generated by Django 5.2.18 on 2026-10-09 18:01

import apps.core.validadores
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_historicalpessoa_cnae_principal_and_more'),
        ('core', '0003_alter_logintegracao_servico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pessoa',
            name='pessoa_doc_unico_empresa',
        ),
        migrations.AddField(
            model_name='historicalpessoa',
            name='emails_documentos',
            field=models.TextField(blank=True, help_text='Separe por vírgula ou ponto e vírgula. Usados no envio de NFS-e, relatórios e pacotes do contrato.', verbose_name='outros e-mails para notas e documentos'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='emails_documentos',
            field=models.TextField(blank=True, help_text='Separe por vírgula ou ponto e vírgula. Usados no envio de NFS-e, relatórios e pacotes do contrato.', verbose_name='outros e-mails para notas e documentos'),
        ),
        migrations.AlterField(
            model_name='historicalpessoa',
            name='cpf_cnpj',
            field=models.CharField(blank=True, help_text='Pode ficar em branco enquanto o CNPJ não existe; a emissão de nota fica bloqueada.', max_length=14, validators=[apps.core.validadores.validar_cpf_cnpj_opcional], verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf_cnpj',
            field=models.CharField(blank=True, help_text='Pode ficar em branco enquanto o CNPJ não existe; a emissão de nota fica bloqueada.', max_length=14, validators=[apps.core.validadores.validar_cpf_cnpj_opcional], verbose_name='CPF/CNPJ'),
        ),
        migrations.AddConstraint(
            model_name='pessoa',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf_cnpj', ''), _negated=True), fields=('empresa', 'cpf_cnpj'), name='pessoa_doc_unico_empresa'),
        ),
    ]
