# Generated by Django 5.2.18 on 2026-10-09 00:37

import django.db.models.deletion
import simple_history.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0002_initial"),
        ("certidoes", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("numero", models.CharField(max_length=40, verbose_name="número")),
                ("objeto", models.TextField()),
                (
                    "modalidade",
                    models.CharField(
                        choices=[
                            ("DISPENSA", "Dispensa"),
                            ("PREGAO", "Pregão"),
                            ("INEXIGIBILIDADE", "Inexigibilidade"),
                            ("CONCORRENCIA", "Concorrência"),
                            ("PRIVADO", "Contrato privado"),
                        ],
                        default="DISPENSA",
                        max_length=20,
                    ),
                ),
                (
                    "processo_administrativo",
                    models.CharField(blank=True, max_length=60),
                ),
                (
                    "fundamento_legal",
                    models.CharField(
                        blank=True,
                        help_text='Ex.: "Lei 14.133/2021, art. 75, II"',
                        max_length=200,
                    ),
                ),
                ("data_assinatura", models.DateField()),
                (
                    "vigencia_inicio",
                    models.DateField(verbose_name="início da vigência"),
                ),
                ("vigencia_fim", models.DateField(verbose_name="fim da vigência")),
                ("valor_global", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "valor_mensal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "forma_faturamento",
                    models.CharField(
                        choices=[
                            ("MENSAL", "Mensal"),
                            ("POR_ENTREGA", "Por entrega"),
                            ("UNICO", "Único"),
                        ],
                        default="MENSAL",
                        max_length=12,
                    ),
                ),
                (
                    "dia_faturamento",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "prazo_pagamento_dias",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="prazo de pagamento (dias)"
                    ),
                ),
                (
                    "indice_reajuste",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="índice de reajuste"
                    ),
                ),
                ("data_base_reajuste", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("VIGENTE", "Vigente"),
                            ("SUSPENSO", "Suspenso"),
                            ("ENCERRADO", "Encerrado"),
                            ("RESCINDIDO", "Rescindido"),
                        ],
                        default="VIGENTE",
                        max_length=12,
                    ),
                ),
                (
                    "discriminacao_padrao",
                    models.TextField(
                        blank=True,
                        help_text="Placeholders: {competencia}, {contrato}, {empenho}, {objeto}.",
                        verbose_name="discriminação padrão",
                    ),
                ),
                (
                    "exige_relatorio_atividades",
                    models.BooleanField(
                        default=True, verbose_name="exige relatório de atividades"
                    ),
                ),
                (
                    "exige_relatorio_sla",
                    models.BooleanField(
                        default=False, verbose_name="exige relatório de SLA"
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        default="#1E5BFF",
                        help_text="Cor usada nos gráficos.",
                        max_length=7,
                    ),
                ),
                (
                    "certidoes_exigidas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="contratos",
                        to="certidoes.tipocertidao",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos",
                        to="cadastros.pessoa",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "fiscal_contrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos_fiscal",
                        to="cadastros.contato",
                    ),
                ),
                (
                    "gestor_contrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos_gestor",
                        to="cadastros.contato",
                    ),
                ),
                (
                    "responsaveis",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Técnicos alocados (veem o contrato no papel Operação).",
                        related_name="contratos_alocados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "contrato",
                "verbose_name_plural": "contratos",
                "ordering": ["-vigencia_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "ano_mes",
                    models.DateField(
                        help_text="Sempre dia 1 do mês.", verbose_name="competência"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta"),
                            ("EM_FATURAMENTO", "Em faturamento"),
                            ("FATURADA", "Faturada"),
                            ("PAGA", "Paga"),
                        ],
                        default="ABERTA",
                        max_length=15,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "pacote_medicao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.anexo",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competencias",
                        to="contratos.contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "competência",
                "verbose_name_plural": "competências",
                "ordering": ["contrato", "ano_mes"],
            },
        ),
        migrations.CreateModel(
            name="Aditivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("numero", models.CharField(max_length=30, verbose_name="número")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PRAZO", "Prazo"),
                            ("VALOR", "Valor"),
                            ("PRAZO_VALOR", "Prazo e valor"),
                            ("REAJUSTE", "Reajuste"),
                            ("OBJETO", "Objeto"),
                        ],
                        max_length=12,
                    ),
                ),
                ("data", models.DateField()),
                (
                    "nova_vigencia_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="novo fim de vigência"
                    ),
                ),
                (
                    "valor_acrescimo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Use valor negativo para supressão.",
                        max_digits=14,
                        null=True,
                        verbose_name="valor de acréscimo",
                    ),
                ),
                (
                    "percentual",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("justificativa", models.TextField(blank=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aditivos",
                        to="contratos.contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "aditivo",
                "verbose_name_plural": "aditivos",
                "ordering": ["data"],
            },
        ),
        migrations.CreateModel(
            name="Empenho",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("numero", models.CharField(max_length=40, verbose_name="número")),
                ("data", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "dotacao_orcamentaria",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="dotação orçamentária"
                    ),
                ),
                ("fonte_recurso", models.CharField(blank=True, max_length=100)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empenhos",
                        to="contratos.contrato",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "empenho",
                "verbose_name_plural": "empenhos",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAditivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                ("numero", models.CharField(max_length=30, verbose_name="número")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PRAZO", "Prazo"),
                            ("VALOR", "Valor"),
                            ("PRAZO_VALOR", "Prazo e valor"),
                            ("REAJUSTE", "Reajuste"),
                            ("OBJETO", "Objeto"),
                        ],
                        max_length=12,
                    ),
                ),
                ("data", models.DateField()),
                (
                    "nova_vigencia_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="novo fim de vigência"
                    ),
                ),
                (
                    "valor_acrescimo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Use valor negativo para supressão.",
                        max_digits=14,
                        null=True,
                        verbose_name="valor de acréscimo",
                    ),
                ),
                (
                    "percentual",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("justificativa", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contratos.contrato",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aditivo",
                "verbose_name_plural": "historical aditivos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCompetencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "ano_mes",
                    models.DateField(
                        help_text="Sempre dia 1 do mês.", verbose_name="competência"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta"),
                            ("EM_FATURAMENTO", "Em faturamento"),
                            ("FATURADA", "Faturada"),
                            ("PAGA", "Paga"),
                        ],
                        default="ABERTA",
                        max_length=15,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contratos.contrato",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pacote_medicao",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.anexo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical competência",
                "verbose_name_plural": "historical competências",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContrato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                ("numero", models.CharField(max_length=40, verbose_name="número")),
                ("objeto", models.TextField()),
                (
                    "modalidade",
                    models.CharField(
                        choices=[
                            ("DISPENSA", "Dispensa"),
                            ("PREGAO", "Pregão"),
                            ("INEXIGIBILIDADE", "Inexigibilidade"),
                            ("CONCORRENCIA", "Concorrência"),
                            ("PRIVADO", "Contrato privado"),
                        ],
                        default="DISPENSA",
                        max_length=20,
                    ),
                ),
                (
                    "processo_administrativo",
                    models.CharField(blank=True, max_length=60),
                ),
                (
                    "fundamento_legal",
                    models.CharField(
                        blank=True,
                        help_text='Ex.: "Lei 14.133/2021, art. 75, II"',
                        max_length=200,
                    ),
                ),
                ("data_assinatura", models.DateField()),
                (
                    "vigencia_inicio",
                    models.DateField(verbose_name="início da vigência"),
                ),
                ("vigencia_fim", models.DateField(verbose_name="fim da vigência")),
                ("valor_global", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "valor_mensal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "forma_faturamento",
                    models.CharField(
                        choices=[
                            ("MENSAL", "Mensal"),
                            ("POR_ENTREGA", "Por entrega"),
                            ("UNICO", "Único"),
                        ],
                        default="MENSAL",
                        max_length=12,
                    ),
                ),
                (
                    "dia_faturamento",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "prazo_pagamento_dias",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="prazo de pagamento (dias)"
                    ),
                ),
                (
                    "indice_reajuste",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="índice de reajuste"
                    ),
                ),
                ("data_base_reajuste", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("VIGENTE", "Vigente"),
                            ("SUSPENSO", "Suspenso"),
                            ("ENCERRADO", "Encerrado"),
                            ("RESCINDIDO", "Rescindido"),
                        ],
                        default="VIGENTE",
                        max_length=12,
                    ),
                ),
                (
                    "discriminacao_padrao",
                    models.TextField(
                        blank=True,
                        help_text="Placeholders: {competencia}, {contrato}, {empenho}, {objeto}.",
                        verbose_name="discriminação padrão",
                    ),
                ),
                (
                    "exige_relatorio_atividades",
                    models.BooleanField(
                        default=True, verbose_name="exige relatório de atividades"
                    ),
                ),
                (
                    "exige_relatorio_sla",
                    models.BooleanField(
                        default=False, verbose_name="exige relatório de SLA"
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        default="#1E5BFF",
                        help_text="Cor usada nos gráficos.",
                        max_length=7,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cadastros.pessoa",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "fiscal_contrato",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cadastros.contato",
                    ),
                ),
                (
                    "gestor_contrato",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cadastros.contato",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical contrato",
                "verbose_name_plural": "historical contratos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEmpenho",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                ("numero", models.CharField(max_length=40, verbose_name="número")),
                ("data", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "dotacao_orcamentaria",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="dotação orçamentária"
                    ),
                ),
                ("fonte_recurso", models.CharField(blank=True, max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contratos.contrato",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical empenho",
                "verbose_name_plural": "historical empenhos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalItemContrato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "descricao",
                    models.CharField(max_length=300, verbose_name="descrição"),
                ),
                ("unidade", models.CharField(default="MES", max_length=20)),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="valor unitário"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contratos.contrato",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical item do contrato",
                "verbose_name_plural": "historical itens do contrato",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ItemContrato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "descricao",
                    models.CharField(max_length=300, verbose_name="descrição"),
                ),
                ("unidade", models.CharField(default="MES", max_length=20)),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="valor unitário"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="contratos.contrato",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "item do contrato",
                "verbose_name_plural": "itens do contrato",
            },
        ),
        migrations.AddConstraint(
            model_name="contrato",
            constraint=models.UniqueConstraint(
                fields=("empresa", "numero", "cliente"), name="contrato_numero_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="competencia",
            constraint=models.UniqueConstraint(
                fields=("contrato", "ano_mes"), name="competencia_unica"
            ),
        ),
    ]
