# Generated by Django 5.2.18 on 2026-10-09 18:10

import django.db.models.deletion
import simple_history.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('core', '0004_historicalcontaemail_contaemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoContrato',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('RELATORIO_ATIVIDADES', 'Relatório de atividades'), ('PLANILHA_CUSTOS', 'Planilha de custos'), ('RELATORIO_SLA', 'Relatório de SLA'), ('NOTA_FISCAL', 'Nota fiscal'), ('CONTRATO', 'Contrato, extrato ou aditivo'), ('OFICIO', 'Ofício, justificativa ou atesto'), ('OUTRO', 'Outro')], max_length=22)),
                ('competencia', models.DateField(blank=True, null=True, verbose_name='competência')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('assinado', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, max_length=300, verbose_name='observação')),
                ('anexo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.anexo')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='contratos.contrato')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
            ],
            options={
                'verbose_name': 'documento do contrato',
                'verbose_name_plural': 'documentos do contrato',
                'ordering': ['-competencia', 'tipo', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocumentoContrato',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('RELATORIO_ATIVIDADES', 'Relatório de atividades'), ('PLANILHA_CUSTOS', 'Planilha de custos'), ('RELATORIO_SLA', 'Relatório de SLA'), ('NOTA_FISCAL', 'Nota fiscal'), ('CONTRATO', 'Contrato, extrato ou aditivo'), ('OFICIO', 'Ofício, justificativa ou atesto'), ('OUTRO', 'Outro')], max_length=22)),
                ('competencia', models.DateField(blank=True, null=True, verbose_name='competência')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('assinado', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, max_length=300, verbose_name='observação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('anexo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.anexo')),
                ('contrato', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contratos.contrato')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical documento do contrato',
                'verbose_name_plural': 'historical documentos do contrato',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
