# Generated by Django 5.2.18 on 2026-10-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_documentocontrato_historicaldocumentocontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='motivo_situacao',
            field=models.CharField(blank=True, editable=False, help_text='Registrado ao inativar ou reativar o contrato.', max_length=300, verbose_name='motivo da situação'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='motivo_situacao',
            field=models.CharField(blank=True, editable=False, help_text='Registrado ao inativar ou reativar o contrato.', max_length=300, verbose_name='motivo da situação'),
        ),
    ]
