# Generated by Django 5.2.18 on 2026-10-09 00:44

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0002_initial"),
        ("catalogo", "0001_initial"),
        ("core", "0002_contador"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalOrcamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "numero",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="número"
                    ),
                ),
                (
                    "cliente_avulso_nome",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="cliente avulso — nome"
                    ),
                ),
                (
                    "cliente_avulso_doc",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        verbose_name="cliente avulso — CPF/CNPJ",
                    ),
                ),
                (
                    "cliente_avulso_contato",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="cliente avulso — e-mail/telefone",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.localdate)),
                ("validade", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("ENVIADO", "Enviado"),
                            ("VISUALIZADO", "Visualizado"),
                            ("APROVADO", "Aprovado"),
                            ("RECUSADO", "Recusado"),
                            ("EXPIRADO", "Expirado"),
                            ("CONVERTIDO", "Convertido em venda"),
                        ],
                        default="RASCUNHO",
                        max_length=12,
                    ),
                ),
                (
                    "condicoes_pagamento",
                    models.CharField(
                        blank=True,
                        default="50% na aprovação e 50% na entrega",
                        max_length=200,
                        verbose_name="condições de pagamento",
                    ),
                ),
                ("prazo_entrega", models.CharField(blank=True, max_length=100)),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "desconto_tipo",
                    models.CharField(
                        choices=[
                            ("VALOR", "Valor (R$)"),
                            ("PERCENTUAL", "Percentual (%)"),
                        ],
                        default="VALOR",
                        max_length=10,
                    ),
                ),
                (
                    "desconto_valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="desconto",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                (
                    "token_publico",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "enviado_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "visualizado_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "aprovado_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "aprovado_por_nome",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                (
                    "ip_aprovacao",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("ajuste_solicitado", models.TextField(blank=True, editable=False)),
                (
                    "followup_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cadastros.pessoa",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pdf",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.anexo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical orçamento",
                "verbose_name_plural": "historical orçamentos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "numero",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="número"
                    ),
                ),
                (
                    "cliente_avulso_nome",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="cliente avulso — nome"
                    ),
                ),
                (
                    "cliente_avulso_doc",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        verbose_name="cliente avulso — CPF/CNPJ",
                    ),
                ),
                (
                    "cliente_avulso_contato",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="cliente avulso — e-mail/telefone",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.localdate)),
                ("validade", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("ENVIADO", "Enviado"),
                            ("VISUALIZADO", "Visualizado"),
                            ("APROVADO", "Aprovado"),
                            ("RECUSADO", "Recusado"),
                            ("EXPIRADO", "Expirado"),
                            ("CONVERTIDO", "Convertido em venda"),
                        ],
                        default="RASCUNHO",
                        max_length=12,
                    ),
                ),
                (
                    "condicoes_pagamento",
                    models.CharField(
                        blank=True,
                        default="50% na aprovação e 50% na entrega",
                        max_length=200,
                        verbose_name="condições de pagamento",
                    ),
                ),
                ("prazo_entrega", models.CharField(blank=True, max_length=100)),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "desconto_tipo",
                    models.CharField(
                        choices=[
                            ("VALOR", "Valor (R$)"),
                            ("PERCENTUAL", "Percentual (%)"),
                        ],
                        default="VALOR",
                        max_length=10,
                    ),
                ),
                (
                    "desconto_valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="desconto",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                (
                    "token_publico",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "enviado_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "visualizado_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "aprovado_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "aprovado_por_nome",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                (
                    "ip_aprovacao",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("ajuste_solicitado", models.TextField(blank=True, editable=False)),
                (
                    "followup_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orcamentos",
                        to="cadastros.pessoa",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "pdf",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.anexo",
                    ),
                ),
            ],
            options={
                "verbose_name": "orçamento",
                "verbose_name_plural": "orçamentos",
                "ordering": ["-data", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="ItemOrcamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "descricao",
                    models.CharField(max_length=500, verbose_name="descrição"),
                ),
                ("variacoes", models.JSONField(blank=True, default=list)),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="preço unitário"
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "item_catalogo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.itemcatalogo",
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="comercial.orcamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "item do orçamento",
                "verbose_name_plural": "itens do orçamento",
                "ordering": ["ordem", "criado_em"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalVenda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "numero",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="número"
                    ),
                ),
                ("cliente_avulso_nome", models.CharField(blank=True, max_length=200)),
                ("data", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta"),
                            ("EM_PRODUCAO", "Em produção"),
                            ("ENTREGUE", "Entregue"),
                            ("FATURADA", "Faturada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ABERTA",
                        max_length=12,
                    ),
                ),
                (
                    "gera_nf",
                    models.BooleanField(default=True, verbose_name="gera nota fiscal"),
                ),
                ("parcelas", models.PositiveSmallIntegerField(default=1)),
                ("primeiro_vencimento", models.DateField(blank=True, null=True)),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cadastros.pessoa",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="comercial.orcamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical venda",
                "verbose_name_plural": "historical vendas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalItemOrcamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "descricao",
                    models.CharField(max_length=500, verbose_name="descrição"),
                ),
                ("variacoes", models.JSONField(blank=True, default=list)),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="preço unitário"
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item_catalogo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogo.itemcatalogo",
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="comercial.orcamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical item do orçamento",
                "verbose_name_plural": "historical itens do orçamento",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "numero",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="número"
                    ),
                ),
                ("cliente_avulso_nome", models.CharField(blank=True, max_length=200)),
                ("data", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta"),
                            ("EM_PRODUCAO", "Em produção"),
                            ("ENTREGUE", "Entregue"),
                            ("FATURADA", "Faturada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ABERTA",
                        max_length=12,
                    ),
                ),
                (
                    "gera_nf",
                    models.BooleanField(default=True, verbose_name="gera nota fiscal"),
                ),
                ("parcelas", models.PositiveSmallIntegerField(default=1)),
                ("primeiro_vencimento", models.DateField(blank=True, null=True)),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendas",
                        to="cadastros.pessoa",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "orcamento",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="venda",
                        to="comercial.orcamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "venda",
                "verbose_name_plural": "vendas",
                "ordering": ["-data", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="ItemVenda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "descricao",
                    models.CharField(max_length=500, verbose_name="descrição"),
                ),
                ("variacoes", models.JSONField(blank=True, default=list)),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "item_catalogo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.itemcatalogo",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="comercial.venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "item da venda",
                "verbose_name_plural": "itens da venda",
            },
        ),
        migrations.CreateModel(
            name="HistoricalItemVenda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("atualizado_em", models.DateTimeField(blank=True, editable=False)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "descricao",
                    models.CharField(max_length=500, verbose_name="descrição"),
                ),
                ("variacoes", models.JSONField(blank=True, default=list)),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.empresa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item_catalogo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogo.itemcatalogo",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="comercial.venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical item da venda",
                "verbose_name_plural": "historical itens da venda",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
